import asyncio
import datetime
from decimal import Decimal

from sqlalchemy import insert

from app.db.session import get_or_create_engine, get_or_create_session
from app.models import Loan, LoanProduct
from app.utils import LoanCurrency, LoanProductType, LoanStage, LoanStatus

loan_products_data = [
    {
        "id": 1,
        "type": LoanProductType.STUDENT_LOAN,
        "description": "A loan for students",
        "loan_amount": {5000, 300000, 525000, 750000},
        "loan_term": {31536000, 157680000, 473040000},
        "apr": Decimal("7.1"),
    },
    {
        "id": 2,
        "type": LoanProductType.AUTO_LOAN,
        "description": "A loan for buying cars",
        "loan_amount": {5000, 300000, 525000, 750000},
        "loan_term": {31536000, 157680000, 473040000},
        "apr": Decimal("2"),
    },
    {
        "id": 3,
        "type": LoanProductType.MORTGAGE_LOAN,
        "description": "A loan for buying a house",
        "loan_amount": {5000, 300000, 525000, 750000},
        "loan_term": {31536000, 157680000, 473040000},
        "apr": Decimal("3.9"),
    },
]

loans_data = [
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "1111111111111111",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 30,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "2222222222222222",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 20,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "3333333333333333",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 10,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "4444444444444444",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "5555555555555555",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "6666666666666666",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "7777777777777777",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "8888888888888888",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "9999999999999999",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_VERIFICATION,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_REVIEW,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "1010101010101010",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_PROCESSING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "1111111122222222",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.UNDERWRITING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "24fa1be5-d62f-4740-8e53-8a7296b2be6f",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "2222222211111111",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.CLOSURE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.APPROVED,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "1906838992840659",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 30,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "5824209195565270",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 20,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "8330156339790414",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 10,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "2997102377146415",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "3180033875704814",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "9409807946944765",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "1692898704237369",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "3152889181645281",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "3736508923913878",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_VERIFICATION,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_REVIEW,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "9514561448974085",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_PROCESSING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "7154552333807534",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.UNDERWRITING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "9f1aef51-7e8e-4f24-981d-62012e86fb6d",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "2754447275635059",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.CLOSURE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.APPROVED,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "7456936005738415",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 30,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "0678835272931858",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 20,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "4522091945920381",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 10,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "0647609698361283",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.ACTIVE,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "1039575284182595",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DEBT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "0103990570731068",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.PAID_OFF,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "5855690234852778",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 1,
        "loan_contract_number": "8628448018168262",
        "amount": 100,
        "currency": LoanCurrency.EUR,
        "stage": LoanStage.NONE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.DRAFT,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "7108043700540247",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_VERIFICATION,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_REVIEW,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "5215918846744777",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.LOAN_PROCESSING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "4440094760706397",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.UNDERWRITING,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.IN_PROGRESS,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
    {
        "user_uuid": "5628d68a-e479-46a6-afeb-3d6f5e89a821",
        "fk_loans_loan_products": 3,
        "loan_contract_number": "3530387063841113",
        "amount": 100,
        "currency": LoanCurrency.USD,
        "stage": LoanStage.CLOSURE,
        "loan_term": datetime.timedelta(weeks=52),
        "loan_status": LoanStatus.APPROVED,
        "loan_guarantors": "John Doe",
        "application_date": datetime.date.today(),
        "updated_at": datetime.date.today(),
        "apr": Decimal("5.1"),
        "paid_amount": 0,
    },
]


async def populate_table() -> None:
    async with get_or_create_session() as session:
        await session.execute(insert(LoanProduct), loan_products_data)

        await session.commit()
        await session.execute(insert(Loan), loans_data)
        await session.commit()
        print("FILLED")


if __name__ == "__main__":
    get_or_create_engine()
    asyncio.run(populate_table())
